> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


### 5 Numpy Function For Statistics

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. Below is some basic introduction what numpy can do.

- np.array is for creating an array.
- np.array is to compute the arithmetic mean along the specified axis.
- np.max / np.amax is to return the maximum of an array or maximum along an axis.
- np.min / np.amin is to return the minimum of an array or minimum along an axis.
- np.concatenate is to join a sequence of arrays along an existing axis.

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [2]:
!pip install jovian --upgrade -q

In [1]:
import jovian

<IPython.core.display.Javascript object>

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mrchmdani/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/mrchmdani/numpy-array-operations


'https://jovian.ai/mrchmdani/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
#function1 = np.array
#function2 = np.mean
#function3 = np.max / np.amax
#function4 = np.min / np.amin
#function5 = np.concatenate

TypeError: unsupported operand type(s) for /: 'function' and 'function'

## Function 1 - np.array

Creating an array

In [6]:
# Example 1 - working (change this)
a = [[1, 2],
     [3, 4], 
     [5, 6]]

np.array(a)

array([[1, 2],
       [3, 4],
       [5, 6]])

You can write array 1D, 2D, 3D, or more vertically or horizontally

In [7]:
# Example 2 - working
b = [[7, 8], [9, 10], [11, 12]]

np.array(b)

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

You can write array 1D, 2D, 3D, or more vertically or horizontally

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
c = [[1, 2],
     [4, 5, 6], 
     [7, 8, 9]]

np.array(c)

/tmp/ipykernel_363/3878011879.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(c)


array([list([1, 2]), list([4, 5, 6]), list([7, 8, 9])], dtype=object)

It broke because the array have different length and shape. You can reduce or add the number so it balance the length or the shape.

Some closing comments about when to use this function.

In [9]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mrchmdani/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/mrchmdani/numpy-array-operations


'https://jovian.ai/mrchmdani/numpy-array-operations'

## Function 2 - np.mean

To compute the arithmetic mean along the specified axis.

In [10]:
# Example 1 - working
a = [[1, 2],
     [3, 4], 
     [5, 6]]

np.mean(a)

3.5

np.mean can be used for 1D, 2D, 3D, or more.

In [11]:
# Example 2 - working
b = [[1, 2, 3],
     [4, 5, 6], 
     [7, 8, 9]]

np.mean(b)

5.0

np.mean can be used for 1D, 2D, 3D, or more.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
c = [[1, 2, 3],
     [4, 5, 6], 
     [7, 8, 9]]

np.mean[c]

TypeError: 'function' object is not subscriptable

Some closing comments about when to use this function.

In [13]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mrchmdani/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/mrchmdani/numpy-array-operations


'https://jovian.ai/mrchmdani/numpy-array-operations'

## Function 3 - np.max

Return the minimum of an array or minimum along an axis.

In [14]:
# Example 1 - working
a = [[7, 2],
     [11, 16], 
     [10, 8]]

np.max(a)

16

np.max is used if you want to looking for highest number in the array

In [15]:
# Example 2 - working
b = [[100, 156, 984],
     [15, 36, 521], 
     [46, 73, 736]]

np.max(b)

984

np.max is used if you want to looking for highest number in the array

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
c = [[7, 2, 46],
     [11, 16, 55], 
     [10, 8, 2]]

np.max()

TypeError: _amax_dispatcher() missing 1 required positional argument: 'a'

It broke because we missing a positional argument. You need to add "c" into the function np.max(c)

Some closing comments about when to use this function.

In [17]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mrchmdani/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/mrchmdani/numpy-array-operations


'https://jovian.ai/mrchmdani/numpy-array-operations'

## Function 4 - ???

Add some explanations

In [18]:
# Example 1 - working
a = [[7, 2],
     [11, 16], 
     [10, 8]]

np.min(a)

2

np.min is used if you want to looking for lowest number in the array

In [19]:
# Example 2 - working
b = [[100, 156, 984],
     [15, 36, 521], 
     [46, 73, 736]]

np.min(b)

15

np.min is used if you want to looking for lowest number in the array

In [20]:
# Example 3 - breaking (to illustrate when it breaks)
c = [[7, 2 46],
     [11, 16, 55], 
     [10, 8, 5]]

np.min(c)

SyntaxError: invalid syntax (1891114134.py, line 2)

It broke because missing comma (,) in the array.

Some closing comments about when to use this function.

In [21]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mrchmdani/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/mrchmdani/numpy-array-operations


'https://jovian.ai/mrchmdani/numpy-array-operations'

## Function 5 - np.concatenate

Join a sequence of arrays along an existing axis.

In [22]:
# Example 1 - working
a = [[1,2],
     [3,4],
     [5,6]]

b = [[7,8],
     [9,10],
     [11,12]]

np.concatenate((a,b),axis=1)

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

Explanation about example

In [23]:
# Example 2 - working
a = [[1,2,13],
     [3,4,14],
     [5,6,15]]

b = [[7,8,16],
     [9,10,17],
     [11,12,18]]

np.concatenate((a,b),axis=1)

array([[ 1,  2, 13,  7,  8, 16],
       [ 3,  4, 14,  9, 10, 17],
       [ 5,  6, 15, 11, 12, 18]])

Explanation about example

In [24]:
# Example 3 - breaking (to illustrate when it breaks)
# Example 2 - working
a = [[1,2],
     [3,4],
     [5,6]]

b = [[7,8,9],
     [10,11,12]]

np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

It broke because the array have different length and shape. You can reduce or add the number so it balance the length or the shape.

Some closing comments about when to use this function.

In [25]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mrchmdani/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/mrchmdani/numpy-array-operations


'https://jovian.ai/mrchmdani/numpy-array-operations'

## Conclusion

Phyton / numphy / coding is fun

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Numpy Array : https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array
* Numpy Statistics : https://numpy.org/doc/stable/reference/routines.statistics.html?highlight=statistic
* Numpy Concatenate : https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html?highlight=concatenate#numpy.concatenate

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>